
#undef DEBUG
#undef DEBUG_CHATTER
#undef NDEBUG
#undef SOUND_SUPPORTS_AIFF
#undef SOUND_SUPPORTS_AU
#undef SOUND_SUPPORTS_MIKMOD
#undef SOUND_SUPPORTS_MODPLUG
#undef SOUND_SUPPORTS_OGG
#undef SOUND_SUPPORTS_RAW
#undef SOUND_SUPPORTS_SHN
#undef SOUND_SUPPORTS_VOC
#undef SOUND_SUPPORTS_WAV
#undef SOUND_SUPPORTS_MIDI
#undef SOUND_SUPPORTS_FLAC
#undef SOUND_SUPPORTS_SMPEG
#undef SOUND_SUPPORTS_MPGLIB
