
#undef DEBUG
#undef DEBUG_CHATTER
#undef NDEBUG
#undef SOUND_SUPPORTS_AIFF
#undef SOUND_SUPPORTS_MOD
#undef SOUND_SUPPORTS_MP3
#undef SOUND_SUPPORTS_OGG
#undef SOUND_SUPPORTS_RAW
#undef SOUND_SUPPORTS_SHN
#undef SOUND_SUPPORTS_VOC
#undef SOUND_SUPPORTS_WAV
#undef SOUND_SUPPORTS_MIDI
