#! /bin/sh

aclocal
libtoolize --automake --copy --force

# rcg09252001 (I ain't got a --force option...?)
#automake --foreign --add-missing --copy --force

automake --foreign --add-missing --copy
autoconf

echo "You are now ready to run ./configure ..."

