#!/bin/sh

set -e
echo "Initial preparation...this can take awhile, so sit tight..."

# MacOS X renames GNU libtool to "glibtool", since they have something
#  else called "libtool" already...
if [ -x /usr/bin/glibtoolize ]; then
  glibtoolize -i -c
else
  libtoolize  -i -c
fi

aclocal -I acinclude
autoheader
automake --foreign --add-missing --copy
autoconf -I acinclude

echo "You are now ready to run ./configure ..."

